---
fixtures:
  repositories:
    apt: https://github.com/puppetlabs/puppetlabs-apt.git
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib.git
    firewall: https://github.com/puppetlabs/puppetlabs-firewall.git
    concat:
      repo: https://github.com/simp/pupmod-simp-concat.git
      branch: 5.X
  symlinks:
    postgresql: "#{source_dir}"
